# //
# // Meta
# //
title: "Talesmith"
description: "Founded by Emmy winning film-maker Martin Williams, our team has a long and glittering track record in producing award-winning content fronted by some of the biggest names in television. Our aim is to deliver the highest quality films and series for UK, US and international broadcasters."
email: "&#105;&#110;&#102;&#111;&#64;&#116;&#97;&#108;&#101;&#115;&#109;&#105;&#116;&#104;&#46;&#116;&#118;" # info@talesmith.tv
email-obfuscated: "&#64;&#116;&#97;&#108;&#101;&#115;&#109;&#105;&#116;&#104;&#46;&#116;&#118;" # @talesmith.tv
telephone: "+44 020 3907 0351"
# //
# // Outputting
# //
timezone: Europe/London
permalink: pretty
muted: false
# //
# // Where things are
# //
url: "https://talesmith.tv/"
source: ./jekyll
destination: ./_site
layouts_dir: /_layouts
data_dir: /_data
# //
# // Assets
# //
images: /img/optimised/
video: /video/
# //
# // Collections
# //
collections:
 work:
  output: true
  permalink: /work/:path/
 about:
  output: true
  permalink: /about/:path/
# //
# // Handling Reading
# //
include: [ '.htaccess', 'humans.txt', 'robots.txt', '.htpasswd' ]
keep_files: [ 'css', 'js', 'img', 'video', 'fonts' ]
exclude:
  - Gulpfile.js
  - readme.md
  - package.json
  - Gemfile
  - Gemfile.lock
  - yarn.lock
  - yarn-error.log
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - run_control
# //
# // Markdown Processors
# //
kramdown:
 auto_ids: false
