backend:
  name: git-gateway
  branch: release

publish_mode: editorial_workflow

media_folder: "/assets/img/"
public_folder: "/img/optimised/"

collections: # A list of collections the CMS should be able to edit
  - name: "work" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "View work" # Used in the UI, ie.: "New Post"
    description: >
      This is where the work posts live.
    folder: "jekyll/_work" # The path to the folder where the documents are stored
    extension: "html"
    sort: "date:desc" # Default is title:asc
    create: true
    delete: true
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Hero image?", name: "hero", widget: "boolean", default: true}
      - {label: "Order", name: "order_page", widget: "number", valueType: "int", min: 1}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Producer", name: "producer", widget: "text"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "work-single"}
      - {label: "Body", name: "body", widget: "markdown"}
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
