backend:
  name: git-gateway
  branch: release

publish_mode: editorial_workflow

media_folder: "assets/img/"
public_folder: "/img/optimised/"

collections: # A list of collections the CMS should be able to edit
  - name: "work" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "View work" # Used in the UI, ie.: "New Post"
    description: >
      This is where the work posts live.
    folder: "jekyll/_work" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true
    delete: true
    slug: "{{slug}}"
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
    fields: # The fields each document in this collection have
      - {label: "Hero video?", name: hero, widget: boolean, default: false}
      - {label: "Loop video?", name: loop, widget: boolean, default: false}
      - {label: "Static image?", name: img, widget: boolean, default: true}
      - {label: "Order", name: "order_page", widget: "number", valueType: "int", min: 1}
      - {label: "Producer", name: "producer", widget: "text"}
      - label: Schema
        name: schema
        required: false
        widget: list
        fields:
          - {label: Type, name: name, widget: string, default: "Director"}
      - label: Cast
        name: cast
        required: false
        widget: list
        fields:
          - {label: Full name, name: name, widget: string}
      - label: Awards
        name: award
        required: false
        widget: list
        fields:
          - {label: Award name, name: name, widget: text}
          - {label: Year, name: year, widget: text}
          - {label: Category, name: category, widget: text}
          - {label: Outcome, name: outcome, widget: select, options: ["Nomination", "Winner"]}
          - {label: Web address, name: url, widget: text}
      - label: Channels
        name: channel
        widget: list
        fields:
          - {label: Channel name, name: name, widget: text}
          - {label: "Text only?", name: text-only, widget: text}
      - label: Map
        name: map
        widget: list
        fields:
          - {label: Location, name: name, widget: text}
          - {label: Latitude, name: lat, widget: text}
          - {label: Longitude, name: long, widget: text}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "work-single"}
      - {label: "Body", name: "body", widget: "markdown"}
